In [2]:
import numpy as np

In [5]:
#Boolean indexing
arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]


In [9]:
len(arr1[arr1<3])

3

In [53]:
names = np.array(["Bob","Joe","Will","Bob","Will","Joe","Joe"])
data = np.random.randint(30,100,(7,4))
print (names)
print (data)

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[72 45 32 92]
 [98 78 31 44]
 [92 69 95 79]
 [61 35 74 96]
 [30 99 37 44]
 [58 39 84 90]
 [32 78 51 54]]


In [19]:
names == "Bob"

array([ True, False, False,  True, False, False, False])

In [20]:
data[names == "Bob"]

array([[84, 31, 76, 82],
       [70, 37, 30, 98]])

In [21]:
data[[0,3]]

array([[84, 31, 76, 82],
       [70, 37, 30, 98]])

In [22]:
data[names=="Bob",2:]

array([[76, 82],
       [30, 98]])

In [25]:
data[names=="Bob",:][0]

array([84, 31, 76, 82])

In [33]:
data[(names=="Bob")|(names=="Will") , :2]

array([[84, 31],
       [89, 56],
       [70, 37],
       [81, 87]])

In [54]:
#90점 초과해야 그 과목 통과, 아니면 통과 못함
#그리고 그 학기 이수를 위해서는 통과한 과목이 1과목 이상이어야 함
#그러면 누가 이번 학기를 이수할 수 있을까?
data[data<80]=0
data[data>=80]=1
data

array([[0, 0, 0, 1],
       [1, 0, 0, 0],
       [1, 0, 1, 0],
       [0, 0, 0, 1],
       [0, 1, 0, 0],
       [0, 0, 1, 1],
       [0, 0, 0, 0]])

In [55]:
np.where(data>0)

(array([0, 1, 2, 2, 3, 4, 5, 5], dtype=int64),
 array([3, 0, 0, 2, 3, 1, 2, 3], dtype=int64))

In [56]:
np.where(data>0)[0]

array([0, 1, 2, 2, 3, 4, 5, 5], dtype=int64)

In [57]:
np.unique(np.where(data>0)[0])

array([0, 1, 2, 3, 4, 5], dtype=int64)

In [59]:
names[np.unique(np.where(data>0)[0])]

array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe'], dtype='<U4')