In [3]:
import numpy

In [2]:
numpy.array([1,2,3])

NameError: name 'numpy' is not defined

In [1]:
import numpy as np

In [3]:
np.array([1,2,3,4])

array([1, 2, 3, 4])

In [4]:
# 파이썬 기본 자료 구조 : 리스트
a = [1,2,3,4,5]
a

[1, 2, 3, 4, 5]

In [6]:
a=[16,17,18,19,20]
b=[]
for i in range(0, len(a)):
    b.append(a[i]+15)
print(b)

[31, 32, 33, 34, 35]


In [7]:
a=np.array(a)
print(a)

[16 17 18 19 20]


In [8]:
a

array([16, 17, 18, 19, 20])

In [9]:
a+15

array([31, 32, 33, 34, 35])

In [10]:
a = [1,2,3,4,5,6,7,8,9,10]
b = [11,12,13,14,15,16,17,18,19,20]
c = []
for i in range(0, len(a),1):
    c.append(a[i]+b[i])
print(c)

[12, 14, 16, 18, 20, 22, 24, 26, 28, 30]


In [11]:
arr_a = np.array(a)
arr_b = np.array(b)

c = arr_a + arr_b
print(c)

[12 14 16 18 20 22 24 26 28 30]


In [14]:
arr = np.array([[1,2,3],[4,5,6,]])
print(arr)
print("\n")
print(arr*arr)
print("\n")
print(arr-arr)
print("\n")
print(arr*10)
print("\n")
print(arr+20)

[[1 2 3]
 [4 5 6]]


[[ 1  4  9]
 [16 25 36]]


[[0 0 0]
 [0 0 0]]


[[10 20 30]
 [40 50 60]]


[[21 22 23]
 [24 25 26]]


In [18]:
print(arr1.ndim)
print(arr1.shape)
print(arr1.dtype)

1
(4,)
float64


In [53]:
arr1 = np.array([6.,7.5,8,0,1])

In [54]:
temp = np.array([1,2,3,], dtype=)

SyntaxError: invalid syntax (<ipython-input-54-7749e78f4bc6>, line 1)

In [20]:
arr3 = np.array([1,2,3], dtype = np.string_)
arr3

array([b'1', b'2', b'3'], dtype='|S1')

In [22]:
# numpy array vs Python Lsit speed
# 물론 조건 및 여러 상황에 따라서 조금 다를 수 있으니 참고!

# 01) 아래는 두 개의 리스트에서 각기 리스트의 합을 구하는 경우
# ( 코드 상 차이가 발생하는 부분들 : range, 리스트에서 +는 리스트 연결이나, numpy에서는 각기 원소들의 합
# 따라서 동일한 역할을 위해서는 리스트에서는for가 필요함

import time
size_vector = 100000

def pythonlist(size_vector):
    t1 = time.time()
    x = range(size_vector)
    y = range(size_vector)
    t2 = time.time()
    print ("python list Load Time : " + str(t2-t1))
    z = []
    
    t3 = time.time()
    for i in range(len(x)):
        z.append(x[i] + y[i])
    t4 = time.time()
    print ("python list for loop : " + str(t4- t3))
    
    print (" Python List Total :" + str(t4 - t1))

    
def numpyarray1(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print ("numpy array1 Load Time : "+str(t2-t1))
    
    t3 = time.time()
    z = x + y
    t4 = time.time()
    print ("numpy array1 for loop : " + str(t4- t3))

    print (" numpy array1 Total :" + str(t4 - t1))

def numpyarray2(size_vector):
    t1 = time.time()
    x = np.arange(size_vector)
    y = np.arange(size_vector)
    t2 = time.time()
    print ("numpy array2 Load Time : "+str(t2-t1))
    
    t3 = time.time()
    z = np.ndarray(size_vector)
    for i in range(len(x)):
        z[i] = x[i] + y[i]
    t4 = time.time()
    print ("numpy array2 for loop : " + str(t4- t3))
    print (" numpy array2 Total :" + str(t4 - t1))

print (" size_vector : 100000")
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print ("------------------------------")

print (" size_vector : 100")
size_vector = 100
pythonlist(size_vector)
numpyarray1(size_vector)
numpyarray2(size_vector)
print ("------------------------------")


#  샘플 결과 
# -->기본적으로 일반적인 list로 생성하는 것이 array로 생성하는 것에 비해서 많은 속도가 소욧된다.
# --> numpy의 백터 연산이 기본적인 for에서 append보다 속도가 빠른 것을 볼 수 있음.
# --> 동잉한 for에 대해서도 상당히 속도가 빠른 것을 볼 수 있다. 
# --> 작은 숫자에서는 큰 차이가 없거나 경우에 따라서 List가 빠를 수도 있음.


# 하나의 예시 결과

#  size_vector : 100000
# python list Load Time : 2.86102294921875e-06
# python list for loop : 0.05470418930053711
#  Python List Total :0.05480003356933594
# numpy array1 Load Time : 0.0014030933380126953
# numpy array1 for loop : 0.0006737709045410156
#  numpy array1 Total :0.002165079116821289
# numpy array2 Load Time : 0.00037980079650878906
# numpy array2 for loop : 1.0013580322265625e-05
#  numpy array2 Total :0.0004830360412597656
# ------------------------------
#  size_vector : 100
# python list Load Time : 3.0994415283203125e-06
# python list for loop : 4.7206878662109375e-05
#  Python List Total :0.00010013580322265625
# numpy array1 Load Time : 5.125999450683594e-05
# numpy array1 for loop : 1.621246337890625e-05
#  numpy array1 Total :0.0001232624053955078
# numpy array2 Load Time : 1.2159347534179688e-05
# numpy array2 for loop : 6.9141387939453125e-06
#  numpy array2 Total :6.818771362304688e-05
# ------------------------------

 size_vector : 100000
python list Load Time : 0.0
python list for loop : 0.024013757705688477
 Python List Total :0.024013757705688477
numpy array1 Load Time : 0.0
numpy array1 for loop : 0.0
 numpy array1 Total :0.0
numpy array2 Load Time : 0.001054525375366211
numpy array2 for loop : 0.0329134464263916
 numpy array2 Total :0.03396797180175781
------------------------------
 size_vector : 100
python list Load Time : 0.0
python list for loop : 0.0
 Python List Total :0.0
numpy array1 Load Time : 0.0
numpy array1 for loop : 0.0
 numpy array1 Total :0.0
numpy array2 Load Time : 0.0
numpy array2 for loop : 0.0
 numpy array2 Total :0.0
------------------------------


In [24]:
list1 = [1,2,3,4,5,6]
arr1 = np.array(list1)
print(list1)
print(arr1)

[1, 2, 3, 4, 5, 6]
[1 2 3 4 5 6]


In [26]:
np.arange(0,6,1)

array([0, 1, 2, 3, 4, 5])

In [39]:
a= np.arange(0,51,10)[:,np.newaxis] + np.arange(0,6,1)
a

array([[ 0,  1,  2,  3,  4,  5],
       [10, 11, 12, 13, 14, 15],
       [20, 21, 22, 23, 24, 25],
       [30, 31, 32, 33, 34, 35],
       [40, 41, 42, 43, 44, 45],
       [50, 51, 52, 53, 54, 55]])

In [35]:
a[0][3:5]

array([3, 4])

In [36]:
a[0,3:5]

array([3, 4])

In [51]:
a[:,2]

array([ 2, 12, 22, 32, 42, 52])

In [47]:
a[2::2, ::2]

array([[20, 22, 24],
       [40, 42, 44]])

In [50]:
a[4:,4:]

array([[44, 45],
       [54, 55]])

In [52]:
arr1 = np.arange(10)
print(arr1)
print(arr1<5)
print(arr1[arr1<5])

[0 1 2 3 4 5 6 7 8 9]
[ True  True  True  True  True False False False False False]
[0 1 2 3 4]
